module.exports = [
  "./gulp/tasks/server",
  "./gulp/tasks/less",
  "./gulp/tasks/font",
  // './gulp/tasks/sass',
  "./gulp/tasks/html",
  "./gulp/tasks/css",
  "./gulp/tasks/scripts",
  "./gulp/tasks/jslibs",
  "./gulp/tasks/jquerylib",
  "./gulp/tasks/allimg",
  "./gulp/tasks/images",
  "./gulp/tasks/svg",
  "./gulp/tasks/copy",
  "./gulp/tasks/clean",
  "./gulp/tasks/build",
]
